name: fluro_annotation_generator_fork
description: >
  Enable annotation support for fluro fork,
  which automatically generate fluro routes for you.
version: 1.0.0
homepage: https://github.com/brianschardt/fluro_annotation_generator

environment:
  sdk: '>=2.4.0 <3.0.0'
  flutter: ">=1.2.0"

dependencies:
  flutter:
    sdk: flutter
  analyzer: ^0.39.8
  build: ^1.2.2
  source_gen: ^0.9.5
  build_config: ^0.4.2
  glob: ^1.2.0
  fluro_fork: ^0.0.1

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.0
  build_runner: any

flutter:
  uses-material-design: false
