name: fluro_annotation_generator_fork
description: >
  Enable annotation support for fluro fork,
  which automatically generate fluro routes for you.
version: 0.0.1
homepage: https://github.com/brianschardt/fluro_annotation_generator
author: brian schardt <brian.ja.schardt@gmail.com

environment:
  sdk: '>=2.4.0 <3.0.0'
  flutter: ">=1.2.0"

dependencies:
  flutter:
    sdk: flutter
  analyzer: any
  build: any
  source_gen: any
  build_config: any
  fluro_fork: ^0.0.1

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.0
  build_runner: any

flutter:
  uses-material-design: false
